# Spring properties
spring:
  application:
     name: oms-service
  datasource:
    url: jdbc:mysql://127.0.0.1/oms
    username: root
    password: mysql   

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port