# Spring properties
spring:
  application:
     name: oms-service
  datasource:
    url: jdbc:mysql://127.0.0.1/oms
    username: root
    password: NewL0g1in  
    test-on-borrow: true
    validation-query: Select 1

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.11.15.10:8761/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port