//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 02:05:50 PM IST 
//


package com.unicommerce.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InventorySnapshot complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InventorySnapshot"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Facility" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OpenSale" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="Inventory" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="OpenPurchase" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="PutawayPending" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="pendingStockTransfer" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InventorySnapshot", propOrder = {
    "facility",
    "openSale",
    "inventory",
    "openPurchase",
    "putawayPending",
    "pendingStockTransfer"
})
public class InventorySnapshot {

    @XmlElement(name = "Facility", required = true)
    protected String facility;
    @XmlElement(name = "OpenSale")
    protected long openSale;
    @XmlElement(name = "Inventory")
    protected long inventory;
    @XmlElement(name = "OpenPurchase")
    protected long openPurchase;
    @XmlElement(name = "PutawayPending")
    protected long putawayPending;
    protected long pendingStockTransfer;

    /**
     * Gets the value of the facility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacility() {
        return facility;
    }

    /**
     * Sets the value of the facility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacility(String value) {
        this.facility = value;
    }

    /**
     * Gets the value of the openSale property.
     * 
     */
    public long getOpenSale() {
        return openSale;
    }

    /**
     * Sets the value of the openSale property.
     * 
     */
    public void setOpenSale(long value) {
        this.openSale = value;
    }

    /**
     * Gets the value of the inventory property.
     * 
     */
    public long getInventory() {
        return inventory;
    }

    /**
     * Sets the value of the inventory property.
     * 
     */
    public void setInventory(long value) {
        this.inventory = value;
    }

    /**
     * Gets the value of the openPurchase property.
     * 
     */
    public long getOpenPurchase() {
        return openPurchase;
    }

    /**
     * Sets the value of the openPurchase property.
     * 
     */
    public void setOpenPurchase(long value) {
        this.openPurchase = value;
    }

    /**
     * Gets the value of the putawayPending property.
     * 
     */
    public long getPutawayPending() {
        return putawayPending;
    }

    /**
     * Sets the value of the putawayPending property.
     * 
     */
    public void setPutawayPending(long value) {
        this.putawayPending = value;
    }

    /**
     * Gets the value of the pendingStockTransfer property.
     * 
     */
    public long getPendingStockTransfer() {
        return pendingStockTransfer;
    }

    /**
     * Sets the value of the pendingStockTransfer property.
     * 
     */
    public void setPendingStockTransfer(long value) {
        this.pendingStockTransfer = value;
    }

}
